version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.5
    commands:
      # Install Terraform manually (pinned version)
      - curl -fsSL -o terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      - unzip terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Entering mc-static directory
      - cd iac/mc-static
      - echo Initializing Terraform
      - terraform init

  build:
    commands:
      - echo Validating Terraform config
      - terraform validate
      - echo Planning infrastructure
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Applying Terraform plan
      - terraform apply -auto-approve tfplan

artifacts:
  files: []
