version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      python: 3.x
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - chmod +x src/mc-setup.sh
      - ./src/mc-setup.sh
